### PR TITLE
Fixed escaping of '%' sign in get_type_metrics

### PR DESCRIPTION
**Pull request by mkluczny**
pull request for issue #57

### CODE REVIEW

**Comment by mkluczny** [comment]
Hi guys,

When can we expect any action on this item?

**Comment by vassilevsky** [comment]
Dear @u338steven, you are the guru of C! Could you verify the changes and drop your opinion? Thanks!

**Comment by u338steven** [comment]
LGTM :)

@vassilevsky
https://github.com/rmagick/rmagick/blob/master/ext/RMagick/rmdraw.c
```static char attrs[] = "OPbcdefghiklmnopqrstuwxyz[@#%";```

```%``` can be removed, but let's fix it some other time.
There is another issue that the number of attributes might increase.
e.g. ```%A```, ```%C```
It is necessary to add them to ```attrs[]``` soon.

About attributes:
Single Letter Attribute Percent Escapes:
```
...
%%   a percent sign
%b   file size of image read in
%c   comment meta-data property
...
```

Long Form Attribute Percent Escapes:
```
%[base]                 base filename, no suffixes (as %t)
%[channels]             ??? channels in use - colorspace ???
%[colorspace]           Colorspace of Image Data (excluding transparency)
...
```

ImageMagick: Format and Print Image Properties - http://www.imagemagick.org/script/escape.php

> WARNING: short form percent escapes are NOT performed when the percent is after a number. For example, 10%x10 does not expand the %x as a percent escape. If you specifically want to expand the 'x', use the long form which overrides this special case. EG: 10%[x]10.

Oh... this is not considered on rmagick...

**Comment by u338steven** [comment]
Sorry I completely forgot to merge this...
Thanks for your contribution!

**Pull request merged**
