### PR TITLE
more robust #177(Fix for ImageMagick 404)

### PR DESCRIPTION
**Pull request by u338steven**
cc @mockdeep

### CODE REVIEW

**Comment by mockdeep** [comment]
lgtm. @u338steven this will help some, though I've seen prior versions change as well. If we can't get them to leave up older versions, maybe we can find a solution where we check for the version we want? I played around with it some but don't have time at the moment:

```sh
curl http://www.imagemagick.org/download/releases/ | grep -o -P \"ImageMagick-6\.9\.0.*?\.tar\.gz\" | xargs echo
```

**Comment by mockdeep** [comment]
@u338steven Do you want to go ahead and merge this?

**Comment by u338steven** [comment]
Sorry for my slow response.

> Do you want to go ahead and merge this?

Yes.

> maybe we can find a solution where we check for the version we want?

Hmm... like this?:
```sh
#!/bin/sh

get_version_list(){
    curl ftp://ftp.imagemagick.org/pub/ImageMagick/releases/ |
    grep -o "ImageMagick-.*tar\.gz$" |
    sed -e "s/ImageMagick-\(.*\)\.tar\.gz$/\1/"
}

is_including(){
    local version_list=$1
    local version=$2

    if echo "${version_list}" | grep "^${version}$" > /dev/null; then
        echo "found ${version}"
        return 0
    else
        echo "not found ${version}"
        return 1
    fi
}

version_list=`get_version_list`

is_including "${version_list}" 6.9.0-1
is_including "${version_list}" 6.9.0-2
is_including "${version_list}" 6.9.0-10
is_including "${version_list}" 6.8.9-5
is_including "${version_list}" 6.8.9-8
is_including "${version_list}" 6.8.9-10

if is_including "${version_list}" 6.6.9-10 ; then
    echo "FOUND"
else
    echo "NOT FOUND"
fi
```

**Comment by mockdeep** [comment]
Something like that. If we could interpolate the version we're looking for into the regex and grab the executable that would be helpful. This is rough, but:

```sh
get_version_list(){
  curl ftp://ftp.imagemagick.org/pub/ImageMagick/releases/
}

find_download_for(list, version){
  echo $version_list | grep version
  return $return_value_of_grep_or_whatever
}

version_list=`get_version_list`

download_uri=find_download_for(version_list, 6.9.0)
```

**Pull request merged**
