### PR TITLE
Fix for ImageMagick 404

### PR DESCRIPTION
**Pull request by mockdeep**
Looks like ImageMagick updated their patch level from `6.8.9-6` to
`6.8.9-10`

### CODE REVIEW

**Comment by mockdeep** [comment]
Bah! They also updated `6.9.0`.

**Comment by mockdeep** [comment]
Anyone opposed to me merging this so I can get my rspec branch passing?

**Comment by vassilevsky** [comment]
Not me! :D

**Comment by mockdeep** [comment]
Okay, merging.

**Pull request merged**
