### PR TITLE
Added missing -alpha remove flag

### LINKED ISSUE #63: Support "-alpha remove" to "flatten" the alpha channel
<a href="https://github.com/tstirrat"></img></a> **Issue by [tstirrat](https://github.com/tstirrat)**
_Wednesday May 21, 2014 at 21:24 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/103_

----

RMagick appears to support most of the options for `img.alpha(type)`, but it doesn't support the **alpha remove** command.

from: http://www.imagemagick.org/Usage/masking/#remove

"The best solution is to use the [Alpha Remove](http://www.imagemagick.org/Usage/masking/#alpha_remove) method to quickly and simply replace the transparency with a background color underlay..."

```
convert a.png   -background skyblue  -alpha remove -alpha off a_remove.jpg
```

At the moment I resort to a workaround:

```ruby
img.border!(0, 0, 'white')
img.alpha Magick::DeactivateAlphaChannel
```

### PR DESCRIPTION
**Pull request by ollie**
Hello,

I tried to add the -alpha remove flag to close #63. Is it correct? Do I need to add tests or other things? I pretty much have no C experience but the change I did works.

Thanks.

### CODE REVIEW

**Comment by vassilevsky** [comment]
Looks like one cannot simply add a new identifier :(

https://travis-ci.org/gemhome/rmagick/jobs/59717747#L5096

**Comment by ollie** [comment]
Humm, what now though? I can't really do anything more. :disappointed:

**Comment by vassilevsky** [comment]
Thank you for making this PR! It's much better than nothing.

Maybe @u338steven knows what to do with it?

**Comment by u338steven** [comment]
@ollie Thanks for your PR!

ImageMagick **6.6.9-10** does not have `RemoveAlphaChannel`, so it should be as below.

rmmain.c:

```c
#if defined(HAVE_ENUM_REMOVEALPHACHANNEL)
        ENUMERATOR(RemoveAlphaChannel)
#endif
```

---

#### about HAVE_ENUM_*

On RMagick, `extconf.rb` generate a header `extconf.h`.

e.g. `CopyAlphaChannel`

extconf.rb:

```rb
      have_enum_values('AlphaChannelType', ['CopyAlphaChannel',                    # 6.4.3-7
                                            'BackgroundAlphaChannel'], headers)    # 6.5.2-5
```

If ImageMagick has `CopyAlphaChannel`, `extconf.h` will be like this:

```c
#ifndef EXTCONF_H
#define EXTCONF_H
...
#define HAVE_ENUM_COPYALPHACHANNEL 1
...

```

`HAVE_ENUM_COPYALPHACHANNEL` is used in rmmain.c:

```c
#if defined(HAVE_ENUM_COPYALPHACHANNEL)
        ENUMERATOR(CopyAlphaChannel)
        ENUMERATOR(ExtractAlphaChannel)
        ENUMERATOR(OpaqueAlphaChannel)
        ENUMERATOR(ShapeAlphaChannel)
        ENUMERATOR(TransparentAlphaChannel)
#endif
```

Therefore, there are no problems even if ImageMagick does not have `CopyAlphaChannel`.

**Comment by vassilevsky** [comment]
You are a SUPERHERO! :D

**Comment by ollie** [comment]
Thanks @u338steven for the info, it makes more sense now. :smile: I've added the check, let's see if it passes.

**Comment by ollie** [comment]
Funny thing, looks like this test is failing now:

```ruby
# test/Magick.rb:54
def test_enumerators
  ary = nil
  assert_nothing_raised do
    ary = Magick::AlphaChannelType.enumerators
  end
  assert_instance_of(Array, ary)
  assert_equal(12, ary.length)
  # ...
```

How do I make it 11 for versions where `remove` is not supported and 12 where it is? :question:

**Comment by vassilevsky** [comment]
I suggest deleting that line. It's not helping.

**Comment by ollie** [comment]
Ok done. The tests now seem to segfault or fail with `failed to allocate memory` (same thing?). Is that normal? :D

**Comment by vassilevsky** [comment]
I head that this is the expected behaviour for C programs :)

Nevertheless, let them finish.

**Comment by vassilevsky** [comment]
Do you know a hosted CI free for OSS that can do similar build matrix but faster?

**Comment by ollie** [comment]
Not really, but a quick search revealed this https://en.wikipedia.org/wiki/Comparison_of_continuous_integration_software and this https://www.quora.com/What-are-the-alternatives-to-Travis-CI. It's probably a matter of picking something and trying it out.

**Comment by vassilevsky** [comment]
Close enough!

**Comment by vassilevsky** [comment]
Thanks Oldřich! You are welcome to send in any other pull requests!

**Comment by ollie** [comment]
No problem, thanks for the help, too.

**Pull request merged**
